# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Snowflake's Repo Documentation
author: Mundodisco8
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/mundodisco8/Snowflake # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Add support for html parsing, as it's used to include images in the MD
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image
    - dollarmath

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org/v2/gh/mundodisco8/Snowflake/HEAD?labpath=docs%2FDesign_Justification.ipynb